services:
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - db
      - ollama
    env_file:
      - .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      OLLAMA_API_URL: http://ollama:11434
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./ai_agents:/app/ai_agents 
    command: ["uvicorn", "backend.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8501:8501"

  ollama:
    image: ollama/ollama:latest
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama/models
    environment:
      - OLLAMA_HOST=http://0.0.0.0:11434
      - OLLAMA_MODELS=/root/.ollama/models

volumes:
  pg_data:
  ollama_models: