sales_data:
  description: > 
    Generate an optimized SQL query to extract relevant data from the table `public.my_sales` based on the question: {question}.  
    Execute the query and return:
      1. The SQL query used to generate the response.
      2. The structured query results.

  expected_output: >
    - The exact SQL query used to answer {question}.
    - The structured results retrieved from executing the query.

  agent: data_assistant

