GROQ_API_KEY="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"
OPENAI_API_KEY="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"
SERPER_API_KEY="296a6cedb74ade5785d7cd3387362148ec0874ed"

